name: flamencoMIR
channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.9
  - ipykernel
  - numpy
  - scipy
  - pandas
  - librosa
  - mir_eval
  - pysoundfile
  - pytorch=2.1
  - torchaudio=2.1
  - cpuonly
  - ffmpeg
  - pip
  - pip:
      - demucs
      - spleeter
      - pesto-pitch
      - essentia