name: audio-separation
channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.10
  - pandas
  - numpy
  - pytorch=2.1
  - torchaudio=2.1
  - cpuonly
  - ffmpeg
  - pip
  - pip:
      - demucs
      - spleeter
      - soundfile
